### ISSUE TITLE
Remove test.check from runtime deps

### ISSUE THREAD

**Issue by kennyjwilli** [wilkerlucio/pathom#111]
Pathom has a runtime dependency on test.check ([here](https://github.com/wilkerlucio/pathom/blob/a50c8ae53102a837553a0414add119ba8e2c7aad/deps.edn#L9)). Is it possible to remove this dependency from runtime? We use spec for validation in our services and don't want someone to accidentally leave in a `fspec` causing it to get generatively checked, ultimately slowing things down. 

It looks like `clojure.test.check.generator` is used in a few places. This can, generally, be replaced by `clojure.spec.gen.alpha` with a few caveats. The spec gen ns does not include some of the test.check functions and none of the macros. We have include a util library that has those functions and macros and will dynamically load test.check if called.

**Comment by wilkerlucio** [comment]
This still required by some parts of the library, is there any reason you can't exclude it?

**Comment by kennyjwilli** [comment]
Even though it is required, in some sense, typically libraries will make test.check a "provided" dependency. 

`edn-query-language.core` has a hard dependency on test.check namespaces.

**Comment by wilkerlucio** [comment]
Yeah, it does because some core operations that require it. Also removing now would be a breaking change for current users. So for those reasons I'm not removing it at this time.

**Comment by kennyjwilli** [comment]
I strongly disagree with this decision. There is a reason clojure.spec dynamically loads test.check -- people don't want it as a runtime dependency. By simply using the `clojure.spec.gen.alpha` instead of test.check namespaces, this would not be a breaking change. 

Further, `:exclusions` is not a viable solution. You cannot load `edn-query-language.core` when you have excluded `org.clojure/test.check`.
