### ISSUE TITLE
Ident existence

### ISSUE THREAD

**Issue by pablodip** [wilkerlucio/pathom#122]
Hello again!

I am trying to see how I could determine the existence of an ident.

Example:

```clojure
(def user-resolver
  (pc/resolver
    `user-resolver
    {::pc/input  #{:user-id}
     ::pc/output [:user-name]}
    (fn [env input]
      (let [user-id (:user-id input)]
        (when (int? user-id)
          {:user-name (str "user" user-id)})))))
```

If I perform `[{[:user-id "1"] [:user-id :user-name]}]`, the user exists, and I can see that because it returns `:user-name`:

```clojure
{[:user-id 1] {:user-name "user1"}}
```

But if I perform `[{[:user-id "b"] [:user-id :user-name]}]` the user does not exist, and I can only see that if I check `:user-name`, since `:user-id` is always returned, no matter what the resolver returns:

```clojure
{[:user-id "b"] {:user-id "b", :user-name :com.wsscode.pathom.core/not-found}}
```

I have tried both `pc/ident-reader` and `pc/parallel-reader` and the result is the same.

Is that the expected behaviour? If so, why?

What should the the way to check existence of idents without having to use other attributes?

Thanks a lot! :)

**Comment by wilkerlucio** [comment]
Hello, I need more context, but I would guess you forgot to register it.

For questions like this (not issues), can you please use the Slack channel instead? This space I prefer to reserve to issues and features. Thanks.
