### ISSUE TITLE
Docs for GraphQL and PC: How to map bettwen GQL and EQL?

### ISSUE THREAD

**Issue by holyjak** [wilkerlucio/pathom#155]
Hello! I have read https://wilkerlucio.github.io/pathom/v2/pathom/2.2.0/graphql/fulcro.html#MultiInputIdents but still strugle mapping from a GQL query that works to an EQL.

Here is the GQL:

```graphql
{subscription(phoneNumber:"123"){
  invoicedService(invoiceId: "fake", serviceCodes: ["fake"]){
    serviceName
  }
  invoice(id: "fake"){
    paid
  }
}}
```
which returns 
```json
{
  "data": {
    "subscription": {
      "invoicedService": null,
      "invoice": null
    }
  },
  "errors": [...]
}
```

Given this definition of my GQL endpoint: 

```clojure
{::pcg/prefix      "channelapi"
 ::pcg/ident-map   {"subscription" {"phoneNumber" :channelapi.subscription/phoneNumber}
                    "invoicedService" {"invoiceId" :channelapi.InvoicedService/invoiceId
                                       "serviceCodes"  :channelapi.InvoicedService/serviceCodes}
;;...
}
```
I have tried the following EQL:

```clojure
(parser env [{[:channelapi.subscription/phoneNumber "123"]
                [:channelapi.SubscriptionData/roles ; <- this works
                 ;; single param field:
                 ;; Note: query->graphql transforms this just fine to
                 ;;   _channelapi_invoice_id_fake: invoice(id: \"fake\") { paid }
                 ;;  so perhaps I don't need to add anything to the ::pcg/ident-map map?
                 {[:channelapi.invoice/id "fake"] [:channelapi.Invoice/paid]}
                 ;; two param field:
                 {'([:channelapi.InvoicedService/invoiceId "fake"]
                    {:pathom/context {:channelapi.InvoicedService/serviceCodes ["fake"]}})
                  [:channelapi.InvoicedService/serviceName]}]}])
;; => 
  ;{[:channelapi.subscription/phoneNumber "123"] 
  ; {:channelapi.SubscriptionData/roles ["USER"]
  ;  [:channelapi.invoice/id "fake"] {}
  ;  [:channelapi.InvoicedService/invoiceId "fake"] {}}}
```

(replacing `:channelapi.InvoicedService` with `:channelapi.invoicedService` everywhere had no effect either)

## Actual behavior

The query sent to the endpoint lacks both `invoice` and `invoicedService` (printed from my driver fn):

```
query {
  _subscription_phoneNumber_123: subscription(phoneNumber: "123") {
    roles
  }
}
```

Also, my custom `validate-connect-key-reader` (thanks!!!) prints this:

```
WARN: trying to read key :channelapi.Invoice/paid which is not available in the index.
WARN: trying to read key :channelapi.InvoicedService/serviceName which is not available in the index.
```

(When I dump the `indexes` atom to a file, I find there e.g. this line `#:channelapi.InvoicedService{:serviceName {},` so it seems to be there?!)

## Expected behavior

The query is transformed to the expected GQL.

## Other observations

When I try to transform the query manually to GQL:

```clojure
(com.wsscode.pathom.graphql/query->graphql
    [{[:channelapi.subscription/phoneNumber "123"]
      [:channelapi.SubscriptionData/roles ; <- this works
       ;; single param field:
       {[:channelapi.invoice/id "fake"] [:channelapi.Invoice/paid]}
       ;; two param field:
       {'([:channelapi.InvoicedService/invoiceId "fake"]
          {:pathom/context {:channelapi.InvoicedService/serviceCodes ["fake"]}})
        [:channelapi.InvoicedService/serviceName]}]}]
    channel-api-gql)

"query {
  _channelapi_subscription_phoneNumber_123: subscription(phoneNumber: \"123\") {
    roles
    _channelapi_invoice_id_fake: invoice(id: \"fake\") {
      paid
    }
    _channelapi_InvoicedService_invoiceId_fake: InvoicedService(invoiceId: \"fake\", context: {serviceCodes: [\"fake\"]}) {
      serviceName
    }
  }
}
"
```

So
1. The `invoice` is included and seems to be just fine
2. The `InvoicedService` starts with upper-case instead of lower-case (does it matter?) and the parameters are wrong, including `context: ...`, instead of "splicing" it in.

I would really appreciate help with troubleshooting this. I'd be happy to contribute to the docs to help future users afterwards.

**Comment by holyjak** [comment]
## Update

The `:pathom/context` is removed from the query by the `remove-pathom-params` at 

https://github.com/wilkerlucio/pathom/blob/7f5ebe0a54431675fe2654621ac0a8f4f952bd9f/src/com/wsscode/pathom/connect/graphql2.cljc#L221

Is that correct?! The params should be used to render the correct graphql query...

The `invoice` and `InvoicedService` parts of the query are removed by this line

https://github.com/wilkerlucio/pathom/blob/7f5ebe0a54431675fe2654621ac0a8f4f952bd9f/src/com/wsscode/pathom/connect/graphql2.cljc#L226

Not sure what's wrong - my query or the code?

Also, the `graphql/query->graphql` obviously does not handle the `:pathom/context` parameters. I see the resolver does not pass the query to it as-is, instead it passes it first through `com.wsscode.pathom.connect.graphql2/build-query` (which calls the `filter-graphql-subquery` shown above, which - wrongly?! - removes the parameter).

**Comment by wilkerlucio** [comment]
Hello, I see you are trying to use the subscription thing around the request, I never tried to use that and I'm afraid its not supported. Had you tried without the subscription part?

The pathom/context is only used in ident queries, and are processed differently, they end up coming as input, so its fine to remove pathom params.

**Comment by holyjak** [comment]
Hi, thanks for your response! What I need to do is to send this GQL query: 

```
{subscription(phoneNumber:"123"){
  invoicedService(invoiceId: "fake", serviceCodes: ["fake"]){
    serviceName
  }
  invoice(id: "fake"){
    paid
  }
}}
```

Are you suggesting I should change my EQL query to this:

```clojure
;[{[:channelapi.subscription/phoneNumber "123"]
  [:channelapi.SubscriptionData/roles ; <- this works
   ;; single param field:
   ;; Note: query->graphql transforms this just fine to
   ;;   _channelapi_invoice_id_fake: invoice(id: \"fake\") { paid }
   ;;  so perhaps I don't need to add anything to the ::pcg/ident-map map?
   {[:channelapi.invoice/id "fake"] [:channelapi.Invoice/paid]}
   ;; two param field:
   {'([:channelapi.InvoicedService/invoiceId "fake"]
      {:pathom/context {:channelapi.InvoicedService/serviceCodes ["fake"]}})
    [:channelapi.InvoicedService/serviceName]}]
;}]
```
??? If I do that, how will Pathom know that it needs the outer `subscription(phoneNumber:"123"){` in the GQL? (Which it needs because `invoice` is not a top-level concept, it only makes sense within the context of a subscription.)

What I am trying to do is to figure out the EQL that produces the desired GQL.

**Comment by holyjak** [comment]
@wilkerlucio Hi, do you have any more insights on how to manage to translate the GQL to EQL? Thank you!!!

**Comment by wilkerlucio** [comment]
I don't know much about subscriptions, but the current implementation doesn't expect it to be there, so its a root conflict in some sense, would require some impl to know about subscriptions directly. The subscriptions I wouldn't not try to handle via Pathom at this moment, you can use the helper `com.wsscode.pathom.graphql/query->graphql` for a more direct transition, but via connect it would a pain to do now, I'll consider this on the next phase of the project (in planing at this moment). 

You can play with the helper I mentioned in this page: https://wilkerlucio.github.io/pathom/v2/pathom/2.2.0/graphql/edn-to-gql.html

So you can try to reproduce your query there. Closing this issue for time being.

**Comment by holyjak** [comment]
Thanks.

If you meant GraphQL Subscriptions than it is a misunderstanding, I most
certainly wasn't trying to use those. I was only trying to pass arguments
to fields https://graphql.org/learn/queries/#arguments

**Comment by wilkerlucio** [comment]
Maybe I was confusing your subscription entry with graphql subscriptions: https://www.apollographql.com/docs/react/data/subscriptions/

Naming issues, hehe, but if its not the case, you should be able to use the helper.
