### ISSUE TITLE
question on resolvers

### ISSUE THREAD

**Issue by podviaznikov** [wilkerlucio/pathom#162]
Let's say I have resolve that takes an input 
`#{:attr1}` and produces `[:attr1 :attr2 :attr3 :attr4 :attr5]`

If my system can resolve entity based on all attributes, how do I do that?

Do I add 4 more resolvers?

input `#{:attr2}` with output `[:attr1 :attr2 :attr3 :attr4 :attr5]`
input `#{:attr3}` with output `[:attr1 :attr2 :attr3 :attr4 :attr5]`
input `#{:attr4}` with output `[:attr1 :attr2 :attr3 :attr4 :attr5]`
input `#{:attr5}` with output `[:attr1 :attr2 :attr3 :attr4 :attr5]`

Or this should be done in a different way?

**Comment by wilkerlucio** [comment]
Yes, you should write all of then, or you can dynamically created those (resolvers are just maps, so its easy to "generate" then). And please prefer to ask questions at #pathom in Clojurians.
