### ISSUE TITLE
onto-chan and to-chan have been deprecated in recent versions of core.async

### ISSUE THREAD

**Issue by eoliphan** [wilkerlucio/pathom#171]
Per the changelog, `onto-chan`  and `to-chan` should be replaced with the new explicit parking (!) or blocking(!!) variants.

**Comment by wilkerlucio** [comment]
Thanks for the hint, PR is welcome if you like to fix this.

**Comment by eoliphan** [comment]
ah heck, i'd planned to but got pulled into some work crap lol

**Comment by wilkerlucio** [comment]
no worries, at least its out already :)
