### ISSUE TITLE
Jar contains js code from shadow-cljs from `resources/public` directory

### ISSUE THREAD

**Issue by geodrome** [wilkerlucio/pathom#178]
I'm trying to reduce the size of my jar and I noticed that the`[com.wsscode/pathom "2.3.0-alpha17"]` jar contains js code from shadow-cljs in `resources` directory. Doesn't seem like it should be there. It takes up ~76M and looks like this:

public
└── js
    └── test
        ├── index.html
        └── js
            ├── cljs-runtime
            ├── manifest.edn
            └── test.js

Same is true of of `[com.wsscode/async "1.0.12"]`

I'll try to use various `exclude` type options in various jar builders, but it seems like it should be addressed at the root.

**Comment by wilkerlucio** [comment]
Hello, I looked but I can't confirm this size, when I see the libraries downloaded from Clojars here I see 9.1MB:
<img width="882" alt="Screen Shot 2020-11-24 at 10 08 07" src="https://user-images.githubusercontent.com/25736/100098613-111e1900-2e3d-11eb-9b27-0a30398a4596.png">

How you get to this number of ~76MB?

**Comment by geodrome** [comment]
I mean if you unzip the jar you'll find js code inside `/public`. I get the same size zipped.

**Comment by wilkerlucio** [comment]
Thanks, fixed on `[com.wsscode/pathom "2.3.0-alpha19"]`
