### ISSUE TITLE
Having a set in parser result causes AbstractMethodError

### ISSUE THREAD

**Issue by awkay** [wilkerlucio/pathom#33]
I'm still trying to give a minimal case, but if you return something that was *not* specified as output and *is* a `set`, then you get an AbstractMethodError.

I'll bring more details soon...wanted to write this down so I would not forget.

**Comment by wilkerlucio** [comment]
@awkay is this still valid?

**Comment by wilkerlucio** [comment]
Closing for now, please reopen if still valid.
