### ISSUE TITLE
Avoid fulcro dependency when using just pathom.graphql

### ISSUE THREAD

**Issue by bwalex** [wilkerlucio/pathom#43]
pathom.graphql has a dependency on fulcro.client.primitives for some tempid detection. I'm not using fulcro, so I'd like to avoid pulling in fulcro for just that function.

**Comment by wilkerlucio** [comment]
Fixed https://github.com/wilkerlucio/pathom/commit/98e229cfe643341ffb3968e0f36ebb8865765366
