### ISSUE TITLE
Supporting front only environnement

### ISSUE THREAD

**Issue by dupuchba** [wilkerlucio/pathom#48]
Hello @wilkerlucio ,

I need to build a cljs front for a client and I don't have access to ther server, only it's REST api :'(.

I wanted to know if you have build `pathom` to be full stack or only efficient on the server side.
Thanks a lot.

**Comment by wilkerlucio** [comment]
Yes, this is an expected usage of it, it can be quite efficient at client-side as well. The latest betas include a new parallel parser that works both on server and client.
