### ISSUE TITLE
add docs for resolver parameters

### ISSUE THREAD

**Issue by wilkerlucio** [wilkerlucio/pathom#64]

**Comment by thenonameguy** [comment]
Do you have any idea how this would be implemented? I was thinking of having self-contained, serializable (so we get Index Explorer/Query component support) schemas defined on the resolver map with Malli or something similar?
https://github.com/metosin/malli

**Comment by wilkerlucio** [comment]
Right now there is the `::pc/params` definition, them the spec itself should be the doc for the parameter, Spec 2 plans to have docs, and in Pathom I'm also adding something for that (WIP at this moment). I'll close this task, when I created I was thinking about auto-complete on the query-editor, and that should go on Pathom Viz instead. Not looking for any rigid schema like Malli at this moment.
