### ISSUE TITLE
Generator on nested placeholders with the same name cause an infinite loop

### ISSUE THREAD

**Issue by felipethome** [wilkerlucio/pathom#73]
When trying to generate data using a placeholder nested in another placeholder with the same name we get:
`Uncaught RangeError: Maximum call stack size exceeded`

**Comment by wilkerlucio** [comment]
I can't reproduce, can you send an example of a query to reproduce the issue?

**Comment by wilkerlucio** [comment]
@felipethome do you remember an actual reproducible example? otherwise I prefer to close this because there is not enough information to work on this issue.

**Comment by felipethome** [comment]
I will try to reproduce it today and tell you.

**Comment by felipethome** [comment]
Closing because I couldn't reproduce it either.
