### ISSUE TITLE
Missing spec for ::resolve in com.wsscode.pathom.connect namespace

### ISSUE THREAD

**Issue by fatihict** [wilkerlucio/pathom#80]
I tried to use `::pc/transform pc/transform-batch-resolver` in a resolver and got the following exception `java.lang.Exception: Unable to resolve spec: :com.wsscode.pathom.connect/resolve`.

**Comment by wilkerlucio** [comment]
Thanks, I guess this one got missing, I'll try to add those soon, in the meantime you can try defining it yourself, a simple `(s/def ::pc/resolve fn?)` should work as a temporary fix.

**Comment by wilkerlucio** [comment]
Fixed 4ff79d9829c90ec7fe2550903f04a22a80e72016
