### ISSUE TITLE
Example without Fulcro?

### ISSUE THREAD

**Issue by Lokeh** [wilkerlucio/pathom#82]
The docs consistently interweave using Fulcro and Pathom. I'd really like to see how to use Pathom outside of the context of Fulcro.

For my use case, I have a Clojure service that needs to merge n queries to the same GraphQL service into one query. I think that I can use Pathom for this but I'm trying to grok the docs and how I would setup everything, since all I really need is the EQL->GraphQL query string.

**Comment by wilkerlucio** [comment]
Now we have the raw section for GraphQL integration: https://wilkerlucio.github.io/pathom/#_raw_components
