### ISSUE TITLE
Make specs removable in CLJS builds

### ISSUE THREAD

**Issue by thheller** [wilkerlucio/pathom#90]
Currently most specs (eg. `pathom.connect`) are unused in `:advanced` compiled builds but since they can't be [removed](https://dev.clojure.org/jira/browse/CLJS-1701) by Closure they end up making builds rather large.

Specs should either be moved into separate namespaces that aren't included in `:advanced` builds or put behind conditionals (eg. `(when INCLUDE-SPECS ...)`.

**Comment by wilkerlucio** [comment]
Fixed 
https://github.com/wilkerlucio/pathom/commit/8404faa4d9b40fa6dce7e78c72cc1edcae3e9a4e
https://github.com/wilkerlucio/pathom/commit/7e3aa46cf0faa2655570057a9c0d6ca12878d20a
