### ISSUE TITLE
Missing params in ast

### ISSUE THREAD

**Issue by fatihict** [wilkerlucio/pathom#93]
I have the following resolver:
```
(pc/defresolver bla [env params]
  {::pc/input #{:bla/id}
   ::pc/output [:bla]}
  (println :ast-params (get-in env [:ast :params]))
  {:bla 5})
```
And I'm doing a load in Fulcro with:
```
(df/load-action env [:bla/id 1] Bla {:params {:foo :bar}})
```
Which results in this query:
```
[({[:bla/id 1] [:bla]} {:foo :bar})]
```
And this AST after running `eql/query->ast`:
```
{:type :root,
 :children [{:type :join,
             :dispatch-key :bla/id,
             :key [:bla/id 1],
             :query [:bla],
             :children [{:type :prop, :dispatch-key :bla, :key :bla}],
             :params {:foo :bar}}]}
```

Which prints `:ast-params nil`. 

I expect this to print `:ast-params {:foo :bar}`

**Comment by fatihict** [comment]
That's good to know. I thought that this was a bug in Fulcro or Pathom. A custom `ident-reader` seems like a good idea, but I think it's weird that it is necessary. I was debugging this for a colleague of mine and he switched to using load-field instead of load which puts the params in the expected location. Thanks for your help Wilker.

**Comment by awkay** [comment]
For F3 perhaps we should move where the params are placed, since Pathom is the recommended?  Could be put in both places in the query to make both fw and bw compatible on F2 and 3.

**Comment by nivekuil** [comment]
For future readers, `load-field!` appears to have the same behavior now as `load!` and won't put the params in the right place for you, so you'll have to go the `:update-query` route.
