### ISSUE TITLE
Lein template for pathom with oge setup

### ISSUE THREAD

**Issue by saurabh-ku** [wilkerlucio/pathom#97]
I am trying to get play around with pathom but having a hard time setting up the project. From the documentation i am able to build and experiment with resolvers but i am unable to connect it with Oge as i don't have much experience with ring or web servers in Clojure (still new to Clojure).

It would be really helpful if there was a lein template that creates a base resolver and required server so we can experiment and get started with pathom quickly.

**Comment by wilkerlucio** [comment]
Hello @saurabh-ku, thanks for the report, I think it makes total sense. Pathom, in the end, is just a parser, the ways in which you can use it are too variable and I agree its overwhelming for a newcomer to setup.

That said, I like to write a template app that demonstrates many usages of pathom as complete setup examples, I hope it can help you and other people looking for it.

I'll see if I can get something of this out this week, I'll keep this thread updated.

Thanks!

**Comment by wilkerlucio** [comment]
Oh, and one important thing, OgE on itself is deprecated, you should look into https://github.com/wilkerlucio/pathom-viz for a query runner.

**Comment by jlesquembre** [comment]
@saurabh-ku you can try https://github.com/jlesquembre/pathom-pedestal if you just want to start quickly a sandbox. See the example project on the `readme`.

It's using OgE, but I want to update the project to use pathom-viz
